**Task 1:** Array Creation Shortcuts
New section

**1.1** Create a 1D array named 'arr1_1' with numbers from 0 to 99 (inclusive) using arange.

**1.2**Create a 3x3 array named 'arr1_2' filled with ones.

**1.3** Create a 2x4 array named 'arr1_3' filled with the number 7.

**1.4** Create a 5x5 array named 'arr1_4' with random integers between 10 and 50 (inclusive).

In [1]:
import numpy as np
arr1_1 = np.arange(100)
arr1_2 = np.ones((3, 3))
arr1_3 = np.full((2, 4), 7)
arr1_4 = np.random.randint(10, 51, size=(5, 5)) # 51 because randint is exclusive on upper bound

print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])

arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[43 42 48 22 31]
 [29 35 27 25 25]]


**Task 2:** Indexing and Slicing with Arrays

**2.1** Extract the element at row 2, column 3 (0-indexed). Store it in 'val2_1'.

**2.2** Extract the first row. Store it in 'row2_2'.

**2.3** Extract the last column. Store it in 'col2_3'.

**2.4** Extract the sub-array consisting of rows 1 and 2, and columns 0 and 1. Store it in 'sub_arr2_4'.

**2.5** Using boolean indexing, select all elements in 'data' that are greater than 100. Store them in 'filtered_elements2_5'.

In [4]:
import numpy as np
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])
val2_1 = data[2, 3]
row2_2 = data[0, :]
col2_3 = data[:, -1]
sub_arr2_4 = data[1:3, 0:2]
filtered_elements2_5 = data[data > 100]

print("val2_1:", val2_1)
print("row2_2:", row2_2)
print("col2_3:", col2_3)
print("sub_arr2_4:\n", sub_arr2_4)
print("filtered_elements2_5:", filtered_elements2_5)


val2_1: 120
row2_2: [10 20 30 40]
col2_3: [ 40  80 120 160]
sub_arr2_4:
 [[ 50  60]
 [ 90 100]]
filtered_elements2_5: [110 120 130 140 150 160]


**Task 3:** Conditional Operations

**3.1** Create a new array 'arr3_2' where elements in 'arr3_1' less than 10 are replaced with 0,and elements greater than or equal to 10 remain unchanged.

**3.2** Count how many elements in 'arr3_1' are even. Store the count in 'even_count3_3'.

In [5]:
import numpy as np
arr3_1 = np.random.randint(1, 21, size=(4, 5))
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)
even_count3_3 = np.sum(arr3_1 % 2 == 0)

print("arr3_1:\n", arr3_1)
print("arr3_2 (elements < 10 replaced with 0):\n", arr3_2)
print("even_count3_3:", even_count3_3)



arr3_1:
 [[ 9  4 20  5  6]
 [ 2 20  3  7 18]
 [19  9 20 20  9]
 [20 11  9 19 13]]
arr3_2 (elements < 10 replaced with 0):
 [[ 0  0 20  0  0]
 [ 0 20  0  0 18]
 [19  0 20 20  0]
 [20 11  0 19 13]]
even_count3_3: 9


**Task 4:** Aggregation Functions

**4.1** Calculate the sum of all elements in 'arr4_1'. Store it in 'sum4_1'.

**4.2** Calculate the mean of each column. Store it in 'mean_cols4_2'.

**4.3** Find the maximum value in each row. Store it in 'max_rows4_3'.

**4.4** Calculate the standard deviation of the entire array. Store it in 'std4_4'.

In [6]:
import numpy as np
arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])
sum4_1 = np.sum(arr4_1)
mean_cols4_2 = np.mean(arr4_1, axis=0)
max_rows4_3 = np.max(arr4_1, axis=1)
std4_4 = np.std(arr4_1)

print("arr4_1:\n", arr4_1)
print("sum4_1:", sum4_1)
print("mean_cols4_2:", mean_cols4_2)
print("max_rows4_3:", max_rows4_3)
print("std4_4:", std4_4)


arr4_1:
 [[10  5 12]
 [ 3  8 15]
 [20  7  4]]
sum4_1: 84
mean_cols4_2: [11.          6.66666667 10.33333333]
max_rows4_3: [12 15 20]
std4_4: 5.2493385826745405


**Task 5:** Reshaping and Flattening

**5.1** Reshape 'arr5_1' into a 4x6 2D array. Store it in 'reshaped_arr5_2'.

**5.2** Reshape 'arr5_1' into a 2x3x4 3D array. Store it in 'reshaped_arr5_3'.

**5.3** Flatten 'reshaped_arr5_2' back into a 1D array. Store it in 'flattened_arr5_4'.Use both `.ravel()` and `.flatten()` to see if there's a difference (though not visible in output).

In [7]:
import numpy as np
arr5_1 = np.arange(24)
reshaped_arr5_2 = arr5_1.reshape(4, 6)
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)
flattened_arr5_4_ravel = reshaped_arr5_2.ravel()
flattened_arr5_4_flatten = reshaped_arr5_2.flatten()
flattened_arr5_4 = flattened_arr5_4_ravel # Using ravel for the stored variable as requested

print("arr5_1 (first 10 elements):", arr5_1[:10])
print("reshaped_arr5_2 (4x6):\n", reshaped_arr5_2)
print("reshaped_arr5_3 (2x3x4):\n", reshaped_arr5_3)
print("flattened_arr5_4 (from ravel):", flattened_arr5_4_ravel[:10])
print("flattened_arr5_4 (from flatten):", flattened_arr5_4_flatten[:10])


arr5_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
reshaped_arr5_2 (4x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
reshaped_arr5_3 (2x3x4):
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
flattened_arr5_4 (from ravel): [0 1 2 3 4 5 6 7 8 9]
flattened_arr5_4 (from flatten): [0 1 2 3 4 5 6 7 8 9]


**Task 6:** Broadcasting

**6.1** Add the 'scalar' to every element of 'arr6_1'. Store it in 'result6_1'.

**6.2** Add the 'vector' to each row of 'arr6_1'. Store it in 'result6_2'.

In [8]:
import numpy as np
arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
scalar = 10
vector = np.array([100, 200, 300])
result6_1 = arr6_1 + scalar
result6_2 = arr6_1 + vector

print("arr6_1:\n", arr6_1)
print("result6_1 (arr6_1 + scalar):\n", result6_1)
print("result6_2 (arr6_1 + vector):\n", result6_2)


arr6_1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
result6_1 (arr6_1 + scalar):
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
result6_2 (arr6_1 + vector):
 [[101 202 303]
 [104 205 306]
 [107 208 309]]


**Task 7:** Copying vs. Viewing Arrays

**7.1** Create a 'view' of 'original_arr7' named 'view_arr7' by slicing the entire array.Modify the first element of 'view_arr7' to 99.Observe how 'original_arr7' changes.

**7.2** Create a 'copy' of 'original_arr7' named 'copy_arr7' using `.copy()`.Modify the last element of 'copy_arr7' to 0.Observe how 'original_arr7' remains unchanged.

In [9]:
import numpy as np
original_arr7 = np.array([1, 2, 3, 4, 5])
view_arr7 = original_arr7[:]
view_arr7[0] = 99

copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0

print("original_arr7 after view modification:", original_arr7)
print("view_arr7:", view_arr7)
print("original_arr7 after copy modification:", original_arr7)
print("copy_arr7:", copy_arr7)


original_arr7 after view modification: [99  2  3  4  5]
view_arr7: [99  2  3  4  5]
original_arr7 after copy modification: [99  2  3  4  5]
copy_arr7: [99  2  3  4  0]


**Task 8**: Stacking and Splitting Arrays

**8.1** Vertically stack 'arr8_a' and 'arr8_b'. Store it in 'vstack_arr8_1'.

**8.2** Horizontally stack 'arr8_a' and 'arr8_b'. Store it in 'hstack_arr8_2'.

**8.3** Vertically stack 'vstack_arr8_1' and 'arr8_c'. Store it in 'combined_arr8_3'.

**8.4** Split 'combined_arr8_3' into 3 equal parts (rows). Store them in 'part1', 'part2', 'part3'.

In [10]:
import numpy as np
arr8_a = np.array([[1, 2]]) # Modified to 1 row
arr8_b = np.array([[3, 4]]) # Modified to 1 row
arr8_c = np.array([[5, 6]]) # Modified to 1 row
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c)) # This will now have 3 rows
part1, part2, part3 = np.vsplit(combined_arr8_3, 3)

print("vstack_arr8_1:\n", vstack_arr8_1)
print("hstack_arr8_2:\n", hstack_arr8_2)
print("combined_arr8_3:\n", combined_arr8_3)
print("part1:\n", part1)
print("part2:\n", part2)
print("part3:\n", part3)

vstack_arr8_1:
 [[1 2]
 [3 4]]
hstack_arr8_2:
 [[1 2 3 4]]
combined_arr8_3:
 [[1 2]
 [3 4]
 [5 6]]
part1:
 [[1 2]]
part2:
 [[3 4]]
part3:
 [[5 6]]


**Task 9**: Sorting and Searching

**9.1** Sort 'arr9_1' in ascending order. Store it in 'sorted_arr9_1'.

**9.2** Sort 'arr9_2d' along columns (i.e., each column sorted independently). Store it in 'sorted_cols9_2'.

**9.3** Find the indices where the value 9 is present in 'arr9_1'. Store it in 'idx9_3'. (Hint: use np.where)

**9.4** Find the index of the maximum value in 'arr9_1'. Store it in 'max_idx9_4'.

In [12]:
import numpy as np
arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])
sorted_arr9_1 = np.sort(arr9_1)
sorted_cols9_2 = np.sort(arr9_2d, axis=0)
idx9_3 = np.where(arr9_1 == 9)
max_idx9_4 = np.argmax(arr9_1)

print("arr9_1:", arr9_1)
print("sorted_arr9_1:", sorted_arr9_1)
print("arr9_2d:\n", arr9_2d)
print("sorted_cols9_2:\n", sorted_cols9_2)
print("idx9_3 (indices of 9):", idx9_3)
print("max_idx9_4 (index of max value):", max_idx9_4)

arr9_1: [5 2 8 1 9 4 7 3 6]
sorted_arr9_1: [1 2 3 4 5 6 7 8 9]
arr9_2d:
 [[30 20 10]
 [60 50 40]
 [90 80 70]]
sorted_cols9_2:
 [[30 20 10]
 [60 50 40]
 [90 80 70]]
idx9_3 (indices of 9): (array([4]),)
max_idx9_4 (index of max value): 4
